# Generated by Django 5.1.4 on 2026-02-27 15:40

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=255)),
                ('available_books', models.IntegerField(default=0)),
                ('sold_books', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'history_table',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('spider_id', models.AutoField(primary_key=True, serialize=False)),
                ('spider_name', models.CharField(max_length=255, unique=True)),
                ('spider_domain', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'source_table',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=255)),
                ('date_scraped', models.DateField(auto_now_add=True)),
                ('first_seen', models.DateField(auto_now_add=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('seller', models.TextField()),
                ('condition', models.TextField()),
                ('editorial', models.TextField()),
                ('images', api.models.SafeJSONField()),
                ('url', models.TextField(unique=True)),
                ('availability', models.BooleanField(default=True)),
                ('interest', models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], db_index=True, default='pending', max_length=20)),
                ('history', models.ForeignKey(db_column='history_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.history')),
            ],
            options={
                'db_table': 'details_table',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='site_id',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.source'),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('site_id', 'isbn'), name='uq_siteid_isbn'),
        ),
    ]
