# Generated by Django 5.1.4 on 2026-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='contact',
            field=models.BooleanField(default=False),
        ),
    ]
